### ISSUE TITLE
Error: val.indexOf is not a function

### ISSUE THREAD

**Issue by kuraga** [bornkiller/angularLocalStorage#3]
Good day, @bornkiller !

I have an error `val.indexOf is not a function` on every digest.
It's from `angularLocalStorage`.

What do you think about?..

**Comment by kuraga** [comment]
@bornkiller , are you here?

**Comment by bornkiller** [comment]
@kuraga 
I will fixed it this week, for a long time working on other things out.

**Comment by kuraga** [comment]
Thanks!

**Comment by kuraga** [comment]
@bornkiller My patch is #4 :smile:

**Comment by kuraga** [comment]
@bornkiller My patch is #7 , merge please! :smile:
